stages:

  dvc_pipeline(End to End):

  cmd:
    - python3 src/feature_engineering.py --config=params.yaml
    - python3

  deps:
    - src/feature_engineering.py
    - data/raw_data/zomato.csv
    - data/processed_data/data_for_processing.csv